dataset:
  name: mnist_math_v2

  root_dir: data
  output_dir: data/mnist_math_v2

  train_size: 50000
  val_size:   10000
  test_size:  10000

  image_height: 28
  symbol_width: 28
  num_symbols:  5

  # v2: tất cả expressions là valid, slot 5 trong ảnh là "?"
  # valid_ratio không còn dùng
  allow_carry: false

  seed: 2026
  save_format: pt