dataset:
  name: mnist_math_v3

  root_dir: data
  output_dir: data/mnist_math_v3

  train_size: 50000
  val_size:   10000
  test_size:  10000

  image_height: 28
  symbol_width: 28
  num_symbols:  4      # [digit1][op1][digit2][=]

  # v3: + và − (110 valid expressions, digit3 perfectly balanced)
  allow_carry: false

  seed: 2026
  save_format: pt